export enum PaperAgree {
  STRONG_ACCEPT = 'STRONG_ACCEPT',
  ACCEPT = 'ACCEPT',
  WEAK_ACCEPT = 'WEAK_ACCEPT',
  BORDERLINE_PAPER = 'BORDERLINE_PAPER',
  WEAK_REJECT = 'WEAK_REJECT',
  REJECT = 'REJECT',
  STRONG_REJECT = 'STRONG_REJECT'
}
